"""Geographic reference + national coverage endpoints.

Read-only. `/geo/states` and `/geo/states/{state_code}/districts` are backed
by `ankur_geo` reference data -- the 36-state identity table (`STATES`) and
the district index derived from the real ingested corpus (`DISTRICTS`, see
`ankur_geo.districts.build_district_index`), not a live query. `/coverage`
combines that same corpus-derived district count with a live read of the
document/rule repositories, so `documents`/`rules`/`approved_rules`/
`unmapped_rules` always reflect what is actually persisted in this
deployment (Postgres in production, in-memory in tests).
"""

from __future__ import annotations

import time
from collections import Counter, defaultdict

from ankur_domain.services import UNBOUNDED_LIMIT, DocumentService, RuleService
from ankur_geo import (
    DISTRICTS,
    STATES,
    District,
    district_key,
    state_by_code,
    state_by_name_or_alias,
    state_key,
)
from ankur_schemas.condition import ConditionCode
from ankur_schemas.enums import ReviewStatus
from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel

from app.deps import get_document_service, get_rule_service

router = APIRouter(tags=["geo"])

# Grouped once at import time: `DISTRICTS` (~650 entries) never changes at
# runtime, it is a committed snapshot regenerated by
# `scripts/generate_geo_reference.py` after a fresh ingest.
_DISTRICTS_BY_STATE: dict[str, list[District]] = defaultdict(list)
for _district in DISTRICTS:
    _DISTRICTS_BY_STATE[_district.state_code].append(_district)


class StateSummary(BaseModel):
    state_code: str
    name: str
    slug: str
    kind: str
    has_dacp_coverage: bool
    document_count: int
    district_count: int


class DistrictSummary(BaseModel):
    district_code: str
    name: str
    slug: str


class CoverageResponse(BaseModel):
    documents: int
    rules: int
    approved_rules: int
    unmapped_rules: int
    districts: int
    district_name_collisions: int
    by_code: dict[str, int]
    by_review_status: dict[str, int]


@router.get("/geo/states")
async def list_states(
    documents_service: DocumentService = Depends(get_document_service),
) -> list[StateSummary]:
    # `has_dacp_coverage`/`district_count` come from `ankur_geo.DISTRICTS`
    # (the corpus-derived reference snapshot) -- cheap and always available,
    # even when Postgres is unreachable. `document_count` is a genuine live
    # count from the document repository (grouped by each document's own
    # `state` text field), not a proxy for `district_count`.
    documents = await documents_service.list(limit=UNBOUNDED_LIMIT, offset=0)
    document_counts: Counter[str] = Counter()
    for document in documents:
        resolved = state_by_name_or_alias(document.state)
        if resolved is not None:
            document_counts[resolved.state_code] += 1

    summaries = []
    for state in STATES:
        districts = _DISTRICTS_BY_STATE.get(state.state_code, [])
        summaries.append(
            StateSummary(
                state_code=state.state_code,
                name=state.name,
                slug=state.slug,
                kind=state.kind.value,
                has_dacp_coverage=bool(districts),
                document_count=document_counts.get(state.state_code, 0),
                district_count=len(districts),
            )
        )
    return summaries


@router.get("/geo/states/{state_code}/districts")
async def list_state_districts(state_code: str) -> list[DistrictSummary]:
    state = state_by_code(state_code)
    if state is None:
        raise HTTPException(status_code=404, detail=f"unknown state code: {state_code!r}")
    return [
        DistrictSummary(district_code=d.district_code, name=d.name, slug=d.slug)
        for d in _DISTRICTS_BY_STATE.get(state.state_code, [])
    ]


# `/coverage` deserializes every extracted_rule's full JSONB payload
# (fields/citation/notes) just to compute two Counters -- at the demo-seed
# scale (~180 rows) that was free; at the full India corpus (~9.4k rows,
# see docs/document-intelligence.md ingestion) a polling frontend hitting
# this on every page load repeatedly re-fetches and re-deserializes the
# entire corpus, which OOM'd the API pod in production (2026-08-28). A
# proper fix is a SQL-side COUNT/GROUP BY repository method (through the
# `RuleRepository` Protocol, implemented in both the memory and Postgres
# repos per this repo's convention -- real feature work, not done here).
# This TTL cache is the minimal fix: the aggregate only needs to be
# eventually-consistent, so recomputing at most once every 30s instead of
# on every request removes the repeated full-corpus fetch entirely.
_COVERAGE_CACHE_TTL_SECONDS = 30.0
_coverage_cache: tuple[float, CoverageResponse] | None = None


@router.get("/coverage")
async def get_coverage(
    documents_service: DocumentService = Depends(get_document_service),
    rules_service: RuleService = Depends(get_rule_service),
) -> CoverageResponse:
    global _coverage_cache
    now = time.monotonic()
    if _coverage_cache is not None:
        cached_at, cached_response = _coverage_cache
        if now - cached_at < _COVERAGE_CACHE_TTL_SECONDS:
            return cached_response

    # Mirrors `trigger_engine.rulestore.RuleStore.coverage()`'s semantics
    # exactly, but reads the persisted document/rule repositories directly
    # instead of re-scanning `data/processed/` from disk on every request.
    documents = await documents_service.list(limit=UNBOUNDED_LIMIT, offset=0)
    rules = await rules_service.list(limit=UNBOUNDED_LIMIT, offset=0)

    by_code: Counter[str] = Counter(
        (rule.fields.condition_code or ConditionCode.UNMAPPED).value for rule in rules
    )
    by_review_status: Counter[str] = Counter(rule.review_status.value for rule in rules)

    district_states: dict[str, set[str]] = defaultdict(set)
    for document in documents:
        district_states[district_key(document.district)].add(state_key(document.state))
    collisions = sum(1 for states in district_states.values() if len(states) > 1)

    response = CoverageResponse(
        documents=len(documents),
        rules=len(rules),
        approved_rules=sum(1 for r in rules if r.review_status == ReviewStatus.APPROVED),
        unmapped_rules=by_code.get(ConditionCode.UNMAPPED.value, 0),
        districts=len(district_states),
        district_name_collisions=collisions,
        by_code=dict(by_code),
        by_review_status=dict(by_review_status),
    )
    _coverage_cache = (now, response)
    return response
