"""Regenerate `packages/geo/src/ankur_geo/_districts_generated.py` from the
ingested DACP corpus (`data/processed/`, gitignored).

Run after re-ingesting the corpus (`make ingest-all-dacp`) so the committed
district reference snapshot -- which resolve_region() and the trigger engine
depend on and which must work even when `data/processed` is absent -- stays
in sync with what has actually been ingested.

Usage:
    uv run python scripts/generate_geo_reference.py [--processed-root PATH]
"""

from __future__ import annotations

import argparse
from pathlib import Path

from ankur_geo.districts import build_district_index

HEADER = '''"""Generated by `scripts/generate_geo_reference.py`. Do not hand-edit.

One `District` per distinct (state, district) pair present in the ingested
DACP corpus at generation time -- see `districts.py` module docstring for why
this is derived from real documents rather than a hand-authored gazetteer.
Regenerate after `make ingest-all-dacp` changes what has been ingested.
"""

from __future__ import annotations

from ankur_geo.districts import District

DISTRICTS: tuple[District, ...] = (
'''

FOOTER = ")\n"


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--processed-root", type=Path, default=Path("data/processed"))
    parser.add_argument(
        "--out",
        type=Path,
        default=Path("packages/geo/src/ankur_geo/_districts_generated.py"),
    )
    args = parser.parse_args()

    districts = build_district_index(args.processed_root)
    if not districts:
        raise SystemExit(
            f"No documents found under {args.processed_root}. Refusing to overwrite "
            f"{args.out} with an empty snapshot -- run `make ingest-all-dacp` first."
        )

    lines = [HEADER]
    for d in districts:
        lines.append(
            f"    District({d.district_code!r}, {d.name!r}, {d.slug!r}, {d.state_code!r}),\n"
        )
    lines.append(FOOTER)

    args.out.write_text("".join(lines), encoding="utf-8")
    print(f"wrote {len(districts)} districts to {args.out}")


if __name__ == "__main__":
    main()
